return {
  c = { 'c', 'glib', 'gl2', 'gl3', 'gl4', 'manpages' },
  cpp = { 'cpp', 'net', 'boost', 'qt', 'cvcpp', 'cocos2dx', 'c', 'manpages' },
  cs = { 'net', 'mono', 'unity3d' },
  css = { 'css', 'bootstrap', 'foundation', 'less', 'awesome', 'cordova', 'phonegap' },
  dart = { 'dartlang', 'polymerdart', 'angulardart' },
  go = { 'go', 'godoc' },
  html = {
    'html', 'angularjs', 'awesome', 'backbone', 'bootstrap', 'cordova', 'css',
    'ember', 'extjs', 'foundation', 'javascript', 'jquery', 'jquerym',
    'jqueryui', 'knockout', 'lodash', 'marionette', 'meteor', 'moo',
    'phonegap', 'prototype', 'sencha', 'statamic', 'svg', 'underscore', 'yui',
    'zepto',
  },
  java = {
    'java', 'cvj', 'grails', 'groovy', 'javadoc', 'javafx', 'playjava',
    'processing', 'spring',
  },
  javascript = {
    'javascript', 'angularjs', 'awsjs', 'backbone', 'bootstrap', 'chai',
    'coffee', 'cordova', 'css', 'd3', 'dojo', 'electron', 'ember', 'express',
    'extjs', 'foundation', 'grunt', 'html', 'jasmine', 'jquery', 'jquerym',
    'jqueryui', 'knockout', 'lodash', 'marionette', 'meteor', 'moment',
    'mongoose', 'moo', 'nodejs', 'phonegap', 'prototype', 'require', 'sencha',
    'sinon', 'sproutcore', 'svg', 'titanium', 'underscore', 'unity3d', 'yui',
    'zepto',
  },
  lua = { 'lua', 'corona' },
  perl = { 'perl', 'manpages' },
  php = {
    'php', 'cakephp', 'codeigniter', 'drupal', 'ee', 'html', 'joomla',
    'laravel', 'mongodb', 'mysql', 'phpp', 'phpunit', 'psql', 'redis',
    'smarty', 'sqlite', 'statamic', 'symfony', 'twig', 'typo3', 'wordpress',
    'yii', 'zend',
  },
  python = {
    'python', 'cvp', 'django', 'flask', 'numpy', 'salt', 'scipy', 'sphinx',
    'sqlalchemy', 'tornado', 'twisted',
  },
  ruby = { 'ruby', 'rubygems', 'rails' },
  sass = { 'sass', 'compass', 'bourbon', 'neat', 'css' },
  scala = { 'scala', 'akka', 'playscala', 'scaladoc' },
  sh = { 'bash', 'manpages' },
  sql = { 'mysql', 'sqlite', 'psql' },
  typescript = { 'typescript', 'javascript', 'nodejs' },
  yaml = { 'chef', 'ansible' }
}
